name: eko_assignment
description: "Assignment App"
publish_to: 'none'

version: 0.1.0+3

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: 1.0.8
  dartz: 0.10.1
  dio: 5.8.0+1
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  freezed_annotation: 2.4.4
  get_it: 7.6.0
  go_router: 14.6.0
  json_annotation: 4.9.0
  local_auth: 2.2.0
  logger: 2.3.0
  pretty_dio_logger: 1.4.0

dev_dependencies:
  build_runner: 2.4.13
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  json_serializable: 6.9.0
  mocktail: 1.0.4


flutter:

  uses-material-design: true
